name: Filters and Events
on:
    workflow_dispatch:
    # schedule:
    #     - cron: "*/59 * * * *"
    push:
        # cant use both can only use one of that
        branches: 
            - main
            - '!feature/*' # ignore pushing to any brabnch name staring with feature usinog !
        # branches-ignore: 
        #     - feature/*
        #     - test/**  # ** ignores multiple / s
    pull_request:
        types: 
            - opened
            - closed
        paths-ignore: 
            - README.md # workflow will only run when a pull request that includes a change on any file other than README.md
        branches: 
            - main.     #confgigurtes your workflow to only run on pull requst that targert specifc branch
jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
            - name: 1st step
              run: echo this workflow/job/step is executed for event type - ${{ github.event_name}}

