name: My First Workflow
on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
              
            - name: Welcome message
              run: echo "Hello Shreyank, 1st Action job"

            - name: List files
              run: ls -l

            - name: Read File
              run: cat README.md