name: My First Workflow
on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: List and Read files # welcome message
              run: |
                echo "Hello Shreyank, 1st Action job"
                ls -ltra
                cat README.md
            
            - name: Generate ASCII Artwork
              run: cawsay -f dragon "Run for cover, I am SHREYANK....RAWR" >> dragon.txt
            # - name: List files
            #   run: ls -l

            # - name: Read File
            #   run: cat README.md