name: Generate ASCII Artwork
on: push

jobs:
  build_job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Install Cowsay Program
        run: sudo apt-get install cowsay -y
      
      - name: Execute Cowsay CMD
        run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt

      # - name: Sleep for 3 Seconds
      #   run: sleep 3
      
      - name: Upload Artifcat
        uses: actions/upload-artifact@v3
        with:
          name: dragon-text-file
          path: dragon.txt
  
  test_job_2:
    needs: build_job_1
    runs-on: ubuntu-latest
    steps:
      # - name: Sleep for 1 Seconds
      #   run: sleep 1

      - name: Download Artifcat
        uses: actions/download-artifact@v3
        with:
          name: dragon-text-file
          path: dragonartifact
        
      # - name: Sleep for 1 Seconds
      #   run: cat dragonartifact/dragon.txt

      - name: Test File Exists
        run: grep -i "dragon" dragonartifact/dragon.txt

  deploy_job_3:
    needs: [test_job_2]
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifcat
        uses: actions/download-artifact@v4
        with:
          name: dragon-text-file
          path: dragonartifact   
          
      - name: Read File
        run: cat dragonartifact/dragon.txt
          
      - name: Deploy
        run: |
          echo Deploying.......
          sleep 2
          echo Deployed......






    # first_job:
    #     runs-on: ubuntu-latest
    #     steps:
    #     - name: Checkout Repo
    #       uses: actions/checkout@v4

    #     - name: List Repo Files
    #       run: ls -ltra

    #     - name: Executing Shell Script
    #       run: | 
    #            chmod +x ascii-script.sh 
    #            ./ascii-script.sh

    

        # - name: Executing Shell Script
        #   run: ./ascii-script.sh     just this it will show error saying permission not found

          
        # steps:
        #     - name: Checkout repo
        #       uses: actions/checkout@v4

        #     - name: Install Cowsay Program
        #       run: sudo apt-get install cowsay -y
            
        #     - name: Execute Cowsay CMD
        #       run: cowsay -f dragon "Run for cover, I am SHREYANK....RAWR" >> dragon.txt
            
        #     - name: Test File's Exstance
        #       run: grep -i "SHREYANK" dragon.txt

        #     - name: Read File
        #       run: cat dragon.txt
            
        #     - name: List Repo file
        #       run: ls -ltra