name: Exploring Manual Workflow

on: 
    schedule:
        - cron: "*/1 * * * *"

env:
    NAME: SHREYANK 
    GAME: CALLOFDUTY

jobs:
    printjob:
        runs-on: ubuntu-latest
        steps:
            - name: Print Name
              run: echo ${{ env.NAME }}
            - name: Print Game
              run: echo ${{ env.GAME }}